### PR TITLE
Fix log tailing, add release process and add various style improvements

### LINKED ISSUE #94: toggle for log tailing is flaky
Sometimes the toggle does not do anything - probably some race condition

### LINKED ISSUE #104: Log view screen
- Change tail mode to use 's' Toggle AutoScroll
- Use 'f' for the full screen logs (esc or f again out from full screen)
- '/' search: when I press esc it should just exit from search  mode

### PR DESCRIPTION
**Pull request by mosonyi**
Fixes 
#94: Log tailing on/off fix 
#104: Log viewing in full-screen possibility
#106: Added a logo
#108: Create a release process
#109: Header infos: Better calculation of system usage real-time + formatting the header.

### CODE REVIEW

File: app/model.go [hunk 1]
```diff
@@ -37,19 +41,26 @@ func InitialModel() *Model {
...
 // Init  will be automatically called by Bubble Tea if the model implements the Model interface
 // and is passed into the tea.NewProgram function.
 func (m *Model) Init() tea.Cmd {
 	// "" loads all stacks on all nodes
-	return tea.Batch(tick(), loadSnapshotAsync(), systeminfoview.LoadStatus())
+	return tea.Batch(
+		tick(), 
+		loadSnapshotAsync(), 
+		systeminfoview.LoadStatus(),
+		m.systemInfo.Init(), // Initialize systeminfo's tick commands
```
Comment (clangenb) [inline app/model.go]: We call 2 times into system view here. If load status is needed in the initialization process, it should be called from within `Init()`.

File: views/logs/handlekey.go [hunk 2]
```diff
@@ -36,10 +53,81 @@ func HandleKey(m *Model, k tea.KeyMsg) tea.Cmd {
...
+		l().Infof("[logsview] 's' key pressed: follow %v -> %v", oldFollow, newFollow)
+		return nil
+	case "f":
+		// toggle fullscreen mode
+		oldFullscreen := m.getFullscreen()
+		newFullscreen := !oldFullscreen
+		m.setFullscreen(newFullscreen)
+		l().Infof("[logsview] 'f' key pressed: fullscreen %v -> %v", oldFullscreen, newFullscreen)
+		return func() tea.Msg {
+			return FullscreenToggledMsg{}
```
Comment (clangenb) [inline views/logs/handlekey.go]: Not sure if this is a good practice. I will investigate it #110

File: app/update.go [hunk 3]
```diff
@@ -117,8 +169,26 @@ func (m *Model) updateViewports(msg tea.Msg) tea.Cmd {
...
+			if logsView.GetFullscreen() || logsView.GetSearchMode() {
+				// Let the view handle esc to exit fullscreen or search mode
+				cmd := m.currentView.Update(msg)
+				return m, cmd
+			}
+		}
+		// Otherwise, go back as normal
+		cmd := m.goBack()
+		return m, cmd
+	}
```
Comment (clangenb) [inline app/update.go]: I don't like this solution about the fullscreen. It mixes up responsibilities in my opinion. However, I think I should solve this in a follow up issue: https://github.com/mosonyi/swarmcli/issues/112

File: docker/info.go [hunk 4]
```diff
@@ -54,77 +55,169 @@ func GetServiceCount() (int, error) {
...
 
-	var totalCPU float64
-	for _, cont := range containers {
+	// Calculate total CPU usage from containers (sample up to 3)
+	var totalCPUPercent float64
+	statsCount := 0
+	maxContainers := len(containers)
+	if maxContainers > 3 {
+		maxContainers = 3
+	}
```
[the remark this answers is not in the document]
Comment (mosonyi) [reply docker/info.go]: Yeah, it's a mistake to get back the CPU and mem results faster. I'll fix it.

File: app/update.go [hunk 5]
```diff
@@ -73,6 +82,21 @@ func (m *Model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
...
+	
+	case systeminfoview.TickMsg:
+		var cmd tea.Cmd
+		cmd = m.systemInfo.Update(msg)
+		return m, cmd
+	
+	case systeminfoview.SpinnerTickMsg:
+		var cmd tea.Cmd
+		cmd = m.systemInfo.Update(msg)
+		return m, cmd
```
[the remark this answers is not in the document]
Comment (mosonyi) [reply app/update.go]: @clangenb Please suggest a fix, or create a follow up issue

File: app/model.go (hunk 1 above)
Comment (mosonyi) [reply app/model.go]: @clangenb please fix/suggest or create a follow-up issue

Comment (clangenb) [reply app/model.go]: https://github.com/mosonyi/swarmcli/issues/113

File: app/update.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (clangenb) [reply app/update.go]: https://github.com/mosonyi/swarmcli/issues/114

File: docker/info.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (clangenb) [reply docker/info.go]: I think it looks good. 👍
